default: &default
  adapter: postgresql
  encoding: UTF-8
  host: localhost
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auth_service_development

test:
  <<: *default
  database: auth_service_test

production:
  <<: *default
  database: auth_service_prod
